stages:
  - mavenbuild
  - maventest
  
maven-build:
  stage: mavenbuild
  tags:
    - springboot_tag
  script:
    - cd Backend/tuhocspring11
    - mvn package
  only:
    refs:
      - BAO_CICD
    changes:
      - Backend/**/*
  
maven-test:
  stage: maventest
  tags:
    - springboot_tag
  script:
    - cd Backend/tuhocspring11
    - mvn test
  only:
    refs:
      - BAO_CICD
    changes:
      - Backend/**/*
